# Generated by Django 2.1.7 on 2019-02-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumnail',
            field=models.FileField(null=True, upload_to='product/images/'),
        ),
    ]
