# Generated by Django 2.1.7 on 2019-02-22 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20190222_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumnail',
            new_name='thumbnail',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
