# Generated by Django 2.1.7 on 2019-02-22 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20190222_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='aaaffff',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
